# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/openshift/origin"
  branch = "release-3.11"

[[override]]
  name = "github.com/openshift/api"
  branch = "release-3.11"

[[override]]
  name = "github.com/openshift/client-go"
  branch = "release-3.11"

[[override]]
  name = "github.com/openshift/library-go"
  branch = "release-3.11"

[[override]]
  name = "k8s.io/api"
  branch = "origin-3.11-kubernetes-1.11.1"
  source = "github.com/openshift/kubernetes-api"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "origin-3.11-kubernetes-1.11.1"
  source = "github.com/openshift/kubernetes-apimachinery"

[[override]]
  name = "k8s.io/kube-aggregator"
  branch = "origin-3.11-kubernetes-1.11.1"
  source = "github.com/openshift/kube-aggregator"

[[override]]
  name = "k8s.io/apiserver"
  branch = "origin-3.11-kubernetes-1.11.1"
  source = "github.com/openshift/kubernetes-apiserver"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "origin-3.11-kubernetes-1.11.1"
  source = "github.com/openshift/kubernetes-apiextensions-apiserver"

[[override]]
  name = "k8s.io/client-go"
  branch = "origin-3.11-kubernetes-1.11.1"
  source = "github.com/openshift/kubernetes-client-go"

[[override]]
  name = "k8s.io/kubernetes"
  branch = "origin-3.11-kubernetes-1.11.1"
  source = "github.com/openshift/kubernetes"

[[override]]
  name = "k8s.io/gengo"
  branch = "origin-3.11-kubernetes-1.11.1"
  source = "github.com/openshift/kubernetes-gengo"

[[override]]
  name = "k8s.io/code-generator"
  branch = "origin-3.11-kubernetes-1.11.1"
  source = "github.com/openshift/kubernetes-code-generator"

[[override]]
  name = "github.com/docker/docker"
  branch = "openshift-3.10-docker-b68221c"
  source = "github.com/openshift/moby-moby"

[[override]]
  name = "github.com/docker/distribution"
  branch = "openshift-3.10-docker-edc3ab2"
  source = "github.com/openshift/docker-distribution"

[prune]
  go-tests = true
  unused-packages = true
