apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-python
  namespace: myproject
spec:
  runLatest:
    configuration:
      build:
        source:
          git:
            url: https://github.com/vdemeester/os-sample-python
            revision: master
        template:
          name: openshift-builds # change that
          arguments:
          - name: IMAGE_STREAM
            value: python:3.6
          - name: IMAGE
            value: docker.io/vdemeester/helloworld-python
          - name: NAME
            value: foo-build
      revisionTemplate:
        spec:
          buildRef:
            apiVersion: build.openshift.io
            kind: BuildConfig
            name: helloworld-python
          container:
            image: docker.io/vdemeester/os-sample-python
            #image: docker-registry.default.svc:5000/myproject/os-sample-python # doesn't work, see OC-199 (I think)
            env:
            - name: BAR
              value: "bar"